---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.17.1
  name: czertainlyclusterissuers.czertainly-issuer.czertainly.com
spec:
  group: czertainly-issuer.czertainly.com
  names:
    kind: CzertainlyClusterIssuer
    listKind: CzertainlyClusterIssuerList
    plural: czertainlyclusterissuers
    singular: czertainlyclusterissuer
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.conditions[?(@.type=="Ready")].status
      name: Ready
      type: string
    - jsonPath: .status.conditions[?(@.type=="Ready")].reason
      name: Reason
      type: string
    - jsonPath: .status.conditions[?(@.type=="Ready")].message
      name: Message
      type: string
    - jsonPath: .status.conditions[?(@.type=="Ready")].lastTransitionTime
      name: LastTransition
      type: date
    - jsonPath: .status.conditions[?(@.type=="Ready")].observedGeneration
      name: ObservedGeneration
      type: integer
    - jsonPath: .metadata.generation
      name: Generation
      type: integer
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: CzertainlyClusterIssuer is the Schema for the clusterissuers
          API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: IssuerSpec defines the desired state of SampleIssuer
            properties:
              apiUrl:
                description: |-
                  ApiUrl is the URL to access CZERTAINLY platform API,
                  for example: "https://my.czertainly.com/api".
                type: string
              authSecretName:
                description: |-
                  AuthSecretName is a reference to a kubernetes.io/tls or Opaque Secret that is
                  used to authenticate and authorize to CZERTAINLY platform.
                  The Secret must be in the same namespace
                  as the referent. If the referent is a ClusterIssuer, the reference instead
                  refers to the resource with the given name in the configured
                  'cluster resource namespace', which is set as a flag on the controller
                  component (and defaults to the namespace that the controller runs in).
                type: string
              caBundleSecretName:
                description: |-
                  CaBundleSecretName is a reference to a Secret that contains the CA bundle to
                  use when verifying the CZERTAINLY platform's serving certificates.
                  The Secret must be in the same namespace as the referent and must
                  contain 'ca.crt' in data. If the referent is a ClusterIssuer, the reference instead
                  refers to the resource with the given name in the configured
                  'cluster resource namespace', which is set as a flag on the controller
                  component (and defaults to the namespace that the controller runs in).
                type: string
              httpTransport:
                description: |-
                  HttpTransport contains settings for HTTP client and transport used to
                  communicate with CZERTAINLY platform API and can be used to override
                  default timeouts and connection settings.
                properties:
                  clientTimeout:
                    description: |-
                      ClientTimeout specifies a time limit for requests made. The timeout includes connection time, any redirects,
                      and reading the response body. A Timeout of zero means no timeout. (default: 30s)
                    type: string
                  dialKeepAlive:
                    description: 'DialKeepAlive specifies the interval between keep-alive
                      probes for an active network connection. (default: 30s)'
                    type: string
                  dialTimeout:
                    description: 'DialTimeout is the maximum amount of time a dial
                      will wait for a connect to complete. (default: 5s)'
                    type: string
                  expectContinueTimeout:
                    description: |-
                      ExpectContinueTimeout, if non-zero, specifies the amount of time to wait for a server's first response headers
                      after fully writing the request headers if the request has an "Expect: 100-continue" header. Zero means
                      no timeout and causes the body to be sent immediately, without waiting for the server to approve.
                      This time does not include the time to send the request header. (default: 1s)
                    type: string
                  idleConnTimeout:
                    description: |-
                      IdleConnTimeout is the maximum amount of time an idle (keep-alive) connection will remain idle before closing
                      itself. Zero means no limit. (default: 90s)
                    type: string
                  maxIdleConns:
                    description: |-
                      MaxIdleConns controls the maximum number of idle (keep-alive) connections across all hosts.
                      Zero means no limit. (default: 200)
                    type: integer
                  maxIdleConnsPerHost:
                    description: |-
                      MaxIdleConnsPerHost, if non-zero, controls the maximum idle (keep-alive) connections to keep
                      per-host. (default: 20)
                    type: integer
                  responseHeaderTimeout:
                    description: |-
                      ResponseHeaderTimeout, if non-zero, specifies the amount of time to wait for a server's response headers
                      after fully writing the request (including its body, if any). This time does not include the time to read
                      the response body. (default: 20s)
                    type: string
                  tlsHandshakeTimeout:
                    description: |-
                      TLSHandshakeTimeout specifies the maximum amount of time to wait for a TLS handshake.
                      Zero means no timeout. (default: 5s)
                    type: string
                type: object
              raProfileName:
                description: |-
                  RaProfileName is the name of the RA profile to use when managing certificates.
                  This is the name of configured RA profile in the CZERTAINLY platform. The user
                  should have permission to use the RA profile.
                type: string
              raProfileUuid:
                description: |-
                  RaProfileUuid is the UUID of the RA profile to use when managing certificates.
                  You can get the UUID of configured RA profile in the CZERTAINLY platform. The user
                  should have permission to use the RA profile.
                type: string
            required:
            - apiUrl
            - authSecretName
            - raProfileUuid
            type: object
          status:
            properties:
              conditions:
                description: |-
                  List of status conditions to indicate the status of an Issuer.
                  Known condition types are `Ready`.
                items:
                  description: Condition contains details for one aspect of the current
                    state of this API Resource.
                  properties:
                    lastTransitionTime:
                      description: |-
                        lastTransitionTime is the last time the condition transitioned from one status to another.
                        This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: |-
                        message is a human readable message indicating details about the transition.
                        This may be an empty string.
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      description: |-
                        observedGeneration represents the .metadata.generation that the condition was set based upon.
                        For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
                        with respect to the current state of the instance.
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      description: |-
                        reason contains a programmatic identifier indicating the reason for the condition's last transition.
                        Producers of specific condition types may define expected values and meanings for this field,
                        and whether the values are considered a guaranteed API.
                        The value should be a CamelCase string.
                        This field may not be empty.
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: type of condition in CamelCase or in foo.example.com/CamelCase.
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
                x-kubernetes-list-map-keys:
                - type
                x-kubernetes-list-type: map
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
